server.port=8080
spring.application.name=project-manager

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/planus
spring.datasource.username=${DB_USER:ulassancakli}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:planUS-super-secret-key-change-in-production-min-256bit}
app.jwt.expiration=86400000
